### ISSUE TITLE
Reset to beginning

### ISSUE THREAD

**Issue by rschuetzler** [tomatoes-app/tomatoes#122] opened 2014-05-29 20:17 UTC
If I get started late in the morning, or perhaps have meetings that interrupt my schedule, I often get off of the Pomodoro schedule. For example, I may have to leave my desk for an hour after the first two 25 minute sessions. When I get back, I would like to start at the beginning rather than in the middle of a 4-session block. Is there, or can there be, a way to reset to the first tomato?

**Comment by rulrok** [comment] 2015-03-16 19:06
Hello, I'm a user of tomatoes and I agree with the above comment. Wouldn't it be possible to detected that after a certain passed period of time, instead of the application start from the middle of a pomodoro sequence, do it from the beginning?
Is there any important reason for not 'fix' this?
Thanks

**Comment by potomak** [comment] 2015-03-16 19:40
@rulrok no, only lack of time at the moment.
If you want to start to develop the feature I'd be happy to review it.

**Comment by rulrok** [comment] 2015-03-16 22:16
I have thought about doing that. Although, not too much free time also, unfortunately.
If a have some time, I will try. o/

**Comment by potomak** [comment] 2015-03-17 03:55
:+1:

**Comment by rulrok** [comment] 2015-05-08 03:24
Hey man, I`m trying to follow the instructions on the readme to set up a virtual box, but the cookbooks thing doesn`t work. (librarian-chef install command). Could you give a look and tell me if I`m doing something wrong? It seems that the url for the configuration file is not working.

**Comment by potomak** [comment] 2015-05-08 03:49
@rulrok I'm not currently using chef, maybe @matteodepalo's help, who introduced those tools, could be more  effective.

Aniway if you want to start working on the project, you just have to be sure to have Mongo DB and Ruby installed.

**Comment by potomak** [comment] 2017-01-31 04:12
@rschuetzler @rulrok do you still need this feature?
I'd need help to delineate the way this feature could work?
Do you anything in mind?

**Comment by potomak** [comment] 2017-01-31 04:19
I think we can consider this issue as a duplicate of https://github.com/tomatoes-app/tomatoes/issues/110. Please follow it if you're still interested.

**Closed by potomak** 2017-01-31 04:19 UTC
Labels: feature, more info needed
